# config.toml
[mqtt]
broker_address = "192.168.0.66"

# Dans Jeedom plugin MQTT l'appareil portera le nom provisoire maisonTpLink compléter par l'adresse ip de l'appareil
topic_name = "/maison/TpLink_"

# "monadressemail" et "monmotdepasse" sont ceux que vous utilisez dans l'application TAPO avec votre téléphone
[tapo]
tapo_username = "monadressemail"
tapo_password = "monmotdepasse"
